version: "3"

services:

  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SUBDOMAINS=$DUCKDNS_SUBDOMAINS
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=true
    volumes:
      - ./duckdns/config:/config

  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Put the STATIC configuration here
      #
      # Use docker
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      # Require every container to enable traefik with label "traefik.enable: true"
      - --providers.docker.exposedByDefault=false
      # Set port number for HTTP
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # Logging
      - --log.level=DEBUG
      # Enable API & Dashboard
      - --api=true
      - --api.dashboard=true
    labels:
      # Put the DYNAMIC configuration here (and use labels for other containers, too)
      #
      traefik.enable: true
      # Create a router for the API & Dashboard
      # \-> HTTPS
      traefik.http.routers.traefik-dashboard-https-router.entrypoints: https
      traefik.http.routers.traefik-dashboard-https-router.rule: Host(`$DOMAIN_NAME`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.traefik-dashboard-https-router.service: api@internal
      # \-> Certificate
      traefik.http.routers.traefik-dashboard-https-router.tls.domains.main: $DOMAIN_NAME
      # \-> Authentication for Dashboard
      traefik.http.middlewares.traefik-dashboard-auth.basicauth.users: $TRAEFIK_DASHBOARD_AUTH
      traefik.http.routers.traefik-dashboard-https-router.middlewares: traefik-dashboard-auth
      # \-> HTTP
      traefik.http.middlewares.traefik-dashboard-redirect.redirectscheme.scheme: https
      traefik.http.routers.traefik-dashboard-http-router.entrypoints: http
      traefik.http.routers.traefik-dashboard-http-router.rule: Host(`$DOMAIN_NAME`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.traefik-dashboard-http-router.middlewares: traefik-dashboard-redirect

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: http
      traefik.http.routers.whoami.rule: Host(`$DOMAIN_NAME`) && PathPrefix(`/whoami`)

  django:
    build: ./django
    command:
      - runserver
      - 0.0.0.0:80
    expose:
      - 80
    environment:
      # Specify the domain name (Required for Django's ALLOWED_HOSTS)
      - DJANGO_ALLOWED_HOSTS=$DOMAIN_NAME
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
    labels:
      traefik.enable: true
      traefik.http.routers.django-http-router.entrypoints: http
      traefik.http.routers.django-http-router.rule: Host(`$DOMAIN_NAME`)
